server:
  port: 8080
  servlet:
    context-path: /cloud

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  cors:
    allowed-origins: "http://localhost:8080,http://localhost:8081"
